# Generated by Django 3.2.9 on 2021-12-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_security_keys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitykey",
            name="attestation",
            field=models.TextField(
                blank=True, help_text="Attestation information", null=True
            ),
        ),
    ]
